#!/bin/bash
set -euo pipefail

branchRegex='^(feat|fix|docs|refactor|chore|test)\/[a-z0-9-]+$'

branch=$(git rev-parse --abbrev-ref HEAD)

if [[ -d ".git/rebase-merge" ]]; then
  branch=$(sed 's|refs/heads/||' .git/rebase-merge/head-name)
fi

if [[ $branch == 'main' ]] || [[ $branch == 'master' ]]; then
  echo "NB! You are commiting directly to main/master"
  exit 0;
fi

if [[ $branch == 'HEAD' ]]; then
  echo "NB! could not find branch name, could be detached head?"
  exit 0;
fi


if ! [[ $branch =~ $branchRegex ]]; then
  echo "Error in pre-commit-hook: Invalid branch name '$branch', must match regex '$branchRegex'"
  exit 1
fi

# OK
exit 0
