#!/bin/bash

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

BRANCH_REGEX='^(feat|fix|docs|refactor|chore|test)\/[a-z0-9-]+$'
if [[ -d ".git/rebase-merge" ]]; then
  BRANCH_NAME=$(sed 's|refs/heads/||' .git/rebase-merge/head-name)
fi

if [[ $BRANCH_NAME == 'main' ]] || [[ $BRANCH_NAME == 'master' ]]; then
  echo "NB! You are commiting directly to main/master"
  exit 0;
fi

if [[ $BRANCH_NAME == 'HEAD' ]]; then
  echo "NB! could not find branch name, could be detached head?"
  exit 0;
fi


if ! [[ $BRANCH_NAME =~ $BRANCH_REGEX ]]; then
  echo "Error in pre-commit-hook: Invalid branch name '$BRANCH_NAME', must match regex '$BRANCH_REGEX'"
  exit 1
fi

# OK
exit 0
